smart_rm/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin


admin.autodiscover()

urlpatterns = [
    url(r'^$', views.delete, name='delete'),
    url(r'^delete/$', views.delete, name='delete'),
    url(r'^tasks/$', views.tasks, name='tasks'),
    url(r'^show/$', views.show, name='show'),
    url(r'^show/trashBin/(?P<pk>\w+)/recover_from_trash$', views.recover, name='recover'),
    url(r'^show/trashBin/(?P<pk>\w+)/remove_from_trash$', views.remove_from_trash, name='remove'),
    url(r'^show/trashBin/(?P<pk>\w+)/$', views.show_trash, name='show'),
    url(r'^history/$', views.history, name='history'),
    url(r'^regex/', views.RegularCreate.as_view(), name='regular'),
    url(r'^settings/$', views.settings_without_bin, name='settings'),
    url(r'^settings/trashBin/(?P<pk>\w+)/$', views.TrashBinUpdate.as_view(), name='settings'),
    url(r'^remove/(?P<pk>\w+)/$', views.TrashBinDelete.as_view(), name='remove'),
    url(r'^add/$', views.TrashBinCreate.as_view(), name='add'),
    url(r'get_info', views.get_info_for_file_system),
    url(r'^success/$', views.success),
    url(r'delete/add_task', views.add_task, name='adding_task'),
    url(r'tasks/execute_task', views.execute_task, name='executing_task'),
    url(r'tasks/delete_task', views.delete_task, name='deleting_task'),
    url(r'tasks/execute_regular_task', views.execute_regular_task, name='executing_regular_task'),
    url(r'tasks/delete_regular_task', views.delete_regular_task, name='deleting_regular_task'),
]

web_rm/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('smart_rm.urls'))
]

smart_rm/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class Trash_bin(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    path_of_trash = models.CharField(max_length=100)
    dried = models.BooleanField()
    silent = models.BooleanField()
    size = models.BigIntegerField()
    time = models.BigIntegerField()
    number = models.BigIntegerField()
    policies = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_name(self):
        return str(self.name)

    def get_data(self):
        return self.path_of_trash


class RegularTask(models.Model):
    regular_expression = models.CharField(max_length=200)
    start_folder = models.CharField(max_length=200)
    current_trash_bin = models.ForeignKey('Trash_bin', on_delete=models.CASCADE)


class Task(models.Model):
    current_trash_bin = models.ForeignKey('Trash_bin', on_delete=models.CASCADE)
    files = models.TextField()
    name_of_operation = models.CharField(max_length=50)
    hashes = models.TextField()


class Log(models.Model):
    text = models.TextField()


class History(models.Model):
    files = models.TextField(null=True, blank=True)
    trash_bin = models.CharField(max_length=200)
    start_folder = models.TextField(null=True, blank=True)
    pattern = models.TextField(null=True, blank=True)
    name_of_operation = models.CharField(max_length=100)
    state = models.CharField(max_length=100)

smart_rm/forms.py
from django import forms
from .models import *


class AddingForm(forms.ModelForm):

    class Meta:
        model = Trash_bin
        exclude = [""]


class SettingForm(forms.ModelForm):

    class Meta:
        model = Trash_bin
        exclude = [""]


class RegularForm(forms.ModelForm):

    class Meta:
        model = RegularTask
        exclude = [""]

smart_rm/views.py
from django.shortcuts import render
# from .forms import *
from .models import *
import os
from django.http import JsonResponse
from .file_system import get_info
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.decorators.csrf import csrf_exempt
import config_changing
import source.src.trash
import source.high_level_operations
import source.src.my_exceptions
import source.src.serialization
from helpful_functions import clean_list, from_list_to_string


@csrf_exempt
def add_task(request):
    data = dict(request.POST)
    current_trash = Trash_bin.objects.get(name=from_list_to_string(data['trash']))
    task_instance = Task(current_trash_bin=current_trash,
                         files=[data_of_file.encode('ascii', 'ignore') for data_of_file in data['files[]']],
                         name_of_operation='Remove to trash')
    task_instance.save()
    return render(request, 'smart_rm/success.html')


@csrf_exempt
def execute_task(request):
    data = dict(request.POST)
    name_of_operation = from_list_to_string(data['operation'])
    files = data['files']
    current_trash_bin = data['trash']
    config_name = 'config_of_' + from_list_to_string(current_trash_bin) + '.cfg'
    my_trash = source.src.trash.Trash(os.path.join(os.path.expanduser('~'), '.Configs_for_web_rm', config_name))
    status = 'Done'
    if name_of_operation == 'Remove from trash':
        try:
            source.high_level_operations.high_deleting_files_from_trash(the_trash=my_trash,
                                                                        list_of_files=clean_list(data, 'hashes'))
        except source.src.my_exceptions.PermissionError:
            status = 'Permission Error'
        except source.src.my_exceptions.NotSuchFileError:
            status = 'No File Error'
        except OSError:
            status = 'OSError'
        except source.src.my_exceptions.RemoveError:
            status = 'Remove Error'
        except KeyError:
            status = 'Key Error'
        finally:
            history_instance = History(files=clean_list(data, 'files'), trash_bin=current_trash_bin,
                                       name_of_operation=name_of_operation,
                                       state=status)
            history_instance.save()
    elif name_of_operation == 'Remove to trash':
        try:
            source.high_level_operations.high_remove(clean_list(files, False), my_trash)
        except source.src.my_exceptions.PermissionError:
            status = 'Permission Error'
        except source.src.my_exceptions.NotSuchFileError:
            status = 'No File Error'
        except OSError:
            status = 'OSError'
        except source.src.my_exceptions.RemoveError:
            status = 'Remove Error'
        except KeyError:
            status = 'Key Error'
        finally:
            history_instance = History(files=clean_list(files, False), trash_bin=current_trash_bin,
                                       name_of_operation=name_of_operation,
                                       state=status)
            history_instance.save()

    elif name_of_operation == 'Recover':
        source.high_level_operations.high_recover(the_trash=my_trash,
                                                  list_of_files=clean_list(data, 'hashes'))
        history_instance = History(files=clean_list(data, 'files'), trash_bin=current_trash_bin, name_of_operation=name_of_operation,
                                   state='Done')
        history_instance.save()

    Task.objects.get(id=data['task_id'][0]).delete()
    return render(request, 'smart_rm/success.html')


@csrf_exempt
def execute_regular_task(request):
    data = dict(request.POST)
    start_folder = from_list_to_string(data['start_folder'])
    pattern = from_list_to_string(data['pattern'])
    current_trash_bin = data['trash']
    config_name = 'config_of_' + from_list_to_string(current_trash_bin) + '.cfg'
    my_trash = source.src.trash.Trash(os.path.join(os.path.expanduser('~'), '.Configs_for_web_rm', config_name))
    source.high_level_operations.high_regular_removing(start_folder=start_folder, pattern=pattern, the_trash=my_trash)
    history_instance = History(pattern=pattern, start_folder=start_folder, trash_bin=current_trash_bin,
                               name_of_operation='Regular removing', state='Done')
    history_instance.save()
    RegularTask.objects.get(id=data['task_id'][0]).delete()
    return render(request, 'smart_rm/success.html')


@csrf_exempt
def delete_regular_task(request):
    data = dict(request.POST)
    RegularTask.objects.get(id=data['task_id'][0]).delete()
    return render(request, 'smart_rm/success.html')


@csrf_exempt
def delete_task(request):
    data = dict(request.POST)
    Task.objects.get(id=data['task_id'][0]).delete()
    return render(request, 'smart_rm/success.html')


@csrf_exempt
def delete(request):
    name_list = Trash_bin.objects.all()
    current_page = 'delete'
    return render(request, 'smart_rm/delete.html', locals())


def show(request):
    name_list = Trash_bin.objects.all()
    current_page = 'show'
    return render(request, 'smart_rm/show.html', locals())


def show_trash(request, pk):
    name_of_database = str(pk) + '.json'
    path_to_database = os.path.join(os.path.expanduser('~'), '.Configs_for_web_rm', name_of_database)
    with open(path_to_database, 'r'):
        arr_json_files = source.src.serialization.load_json(path_to_database)
    return render(request, 'smart_rm/show_trash.html', locals())


def tasks(request):
    current_page = 'tasks'
    name_list = Trash_bin.objects.all()
    regular_tasks = reversed(RegularTask.objects.all())
    tasks_list = reversed(Task.objects.all())
    return render(request, 'smart_rm/tasks.html', locals())


@csrf_exempt
def recover(request, pk):
    data = dict(request.POST)
    task_instance = Task(files=data['names[]'], current_trash_bin=Trash_bin.objects.get(name=pk),
                         hashes=data['hashes[]'], name_of_operation='Recover')
    task_instance.save()
    return render(request, 'smart_rm/success.html')


@csrf_exempt
def remove_from_trash(request, pk):
    data = dict(request.POST)
    task_instance = Task(files=data['names[]'], current_trash_bin=Trash_bin.objects.get(name=pk),
                         hashes=data['hashes[]'], name_of_operation='Remove from trash')
    task_instance.save()
    return render(request, 'smart_rm/success.html')


def history(request):
    current_page = 'history'
    history_list = reversed(History.objects.all())


    return render(request, 'smart_rm/history.html', locals())


def settings_without_bin(request):
    current_page = 'settings'
    name_list = Trash_bin.objects.all()
    return render(request, 'smart_rm/settings.html', locals())


def regex(request):
    current_page = 'history'
    name_list = Trash_bin.objects.all()
    return render(request, 'smart_rm/regex.html', locals())


def get_info_for_file_system(request):
    current_id = request.GET['id']
    if current_id == '#':
        home = os.path.expanduser('~')
        return JsonResponse(get_info(home), safe=False)
    else:
        return JsonResponse(get_info(current_id), safe=False)


def get_trash_bin(request, trashBin):
    cur_trash = Trash_bin.objects.get(name=trashBin)
    return cur_trash


def success(request):
    name_list = Trash_bin.objects.all()
    return render(request, 'smart_rm/success.html', locals())



class TrashBinCreate(CreateView):
    model = Trash_bin
    template_name = 'smart_rm/add.html'
    fields = '__all__'
    success_url = "/success/"

    def get_context_data(self, **kwargs):
        data = super(CreateView, self).get_context_data(**kwargs)
        data['name_list'] = Trash_bin.objects.all()
        return data

    def get_form_kwargs(self):
        kwargs = super(TrashBinCreate, self).get_form_kwargs()
        try:
            kwargs['data']['dried']
            dried = True
        except KeyError:
            dried = False

        try:
            kwargs['data']['silent']
            silent = True
        except KeyError:
            silent = False

        try:
            config_changing.make_config(name_of_trash_bin=kwargs['data']['name'],
                                        path_of_trash_bin=kwargs['data']['path_of_trash'],
                                        max_size=int(kwargs['data']['size']), max_time=int(kwargs['data']['time']),
                                        max_num=int(kwargs['data']['number']), policies=kwargs['data']['policies'],
                                        dried=dried, silent=silent)
        except KeyError:
            pass
        return kwargs


class TrashBinUpdate(UpdateView):
    name_list = Trash_bin.objects.all()
    model = Trash_bin
    template_name = 'smart_rm/settings_with_trash_bin.html'
    fields = '__all__'
    success_url = "/success/"

    def get_context_data(self, **kwargs):
        data = super(UpdateView, self).get_context_data(**kwargs)
        data['name_list'] = Trash_bin.objects.all()
        return data

    def get_form_kwargs(self):
        kwargs = super(TrashBinUpdate, self).get_form_kwargs()
        current_silent = None
        current_dried = None
        try:
            if (kwargs['data']['dried']):
                current_dried = True
        except KeyError:
            current_dried = False

        try:
            if (kwargs['data']['silent']):
                current_silent = True
        except KeyError:
            current_silent = False

        try:
            config_changing.make_config(name_of_trash_bin=kwargs['data']['name'],
                                        path_of_trash_bin=kwargs['data']['path_of_trash'],
                                        max_size=int(kwargs['data']['size']), max_time=int(kwargs['data']['time']),

smart_rm/templates/smart_rm/add.html
{% extends "smart_rm/base.html" %}

{% block content %}
<style>
    .add-style{
        height: 500px;
    }
</style>
    <div class="add-style">
        <form method="post" action="" class="form-inline text-center"> {% csrf_token %}
            <div class="container">
                <div class="form-group">
                    {{form.as_p}}
                    <button class="btn btn-primary" type="submit">Add </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

smart_rm/templates/smart_rm/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title>SMART RM</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jstree/3.3.3/themes/default/style.min.css" />
        <script src="//cdnjs.cloudflare.com/ajax/libs/jstree/3.3.3/jstree.min.js"></script>
       <div class="jumbotron">
            <h1>Smart Remover</h1>
            <p>Smart Remover's WEB-interface</p>
       </div>
        <style>
    ul.nb-top {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li.li-nb-top {
    float: left;
}

li a.li-nb-top-a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a.li-nb-top-a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}

ul.nb-top-2 {

    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #2e6da4;
}
li.li-nb-top-2 {
    float: left;
}

li a.li-nb-top-2-a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a.li-nb-top-2-a:hover:not(.active) {
    background-color: #159;
}

.li-nb-top-2-a.active {
    background-color: #3CEF50;
}


.general-container{
    background-color: #eee;
}


.page-header{
    text-align: center;
}
.jumbotron{
    margin-bottom: 0;
    padding-bottom: 10px;
    padding-top: 10px;
}
.smart-head
</style>
    </head>

<body>
    <div class="general-container">
        <nav class="navbar navbar-inverse">
            <ul class="nb-top">
                <li class="li-nb-top"><a class="li-nb-top-a" href="/delete">Delete</a></li>
                <li class="li-nb-top"><a class="li-nb-top-a" href="/regex">Regular</a></li>
                <li class="li-nb-top"><a class="li-nb-top-a" href="/show">Show</a></li>
                <li class="li-nb-top"><a class="li-nb-top-a" href="/tasks">List of tasks</a></li>
                <li class="li-nb-top"><a class="li-nb-top-a" href="/settings">Settings</a></li>
                <li class="li-nb-top"><a class="li-nb-top-a" href="/add">Add</a></li>
                <li class="li-nb-top"><a class="li-nb-top-a" href="/history">History</a></li>
            </ul>
        </nav>


    
    {% block content %}
    {% endblock %}

    </div>
</body>


<!-- jQuery -->
</html>

smart_rm/templates/smart_rm/delete.html
{% extends "smart_rm/base.html" %}

{% block content %}
<div>
<div class="container">
    <div class="row col-lg-offset-14">
<select id="id_current_trash_bin">
    {% for name in name_list %}
    <option value='{{name}}'>{{name}}</option>
    {% endfor %}
</select>
        <button class="btn bg-primary" id="delete_button">Delete!</button>
    </div>
</div>
</div>
<form method="post" action="" class="form-inline text-center"> {% csrf_token %}
            <div class="container">
                <div class="form-group">
                    {{form.current_trash_bin}}
                </div>
            </div>
        </form>


<div id="container-tree">

</div>
<script>
$('#container-tree').jstree({
    "plugins": ["wholerow", "state","json_data"],
'core' : {
    'data': {
        "url": "get_info",
        "data": function (node) {
            return {"id": node.id, "text" : node.text};
        }
    }
}
});

$('#delete_button').on('click', function (event) {
    var current_trash =  $("#id_current_trash_bin").val();
    event.preventDefault();
    var selectedElmsIds = $('#container-tree').jstree("get_selected");

var data = {
    trash : current_trash,
    files : selectedElmsIds
};
console.log(data);
    $.post('add_task', data);
});


</script><script src="../../static/css/dist/jstree.min.js"></script>
{% endblock %}

smart_rm/templates/smart_rm/history.html
{% extends "smart_rm/base.html" %}
{% load my_template_tag %}
{% block content %}
<table class="table table-striped">
    <thead>
      <tr>
          <th>Files</th>
          <th>Regular expression</th>
          <th>Start folder</th>
          <th>Operation</th>
          <th>Trash bin</th>
          <th>State</th>
      </tr>
    </thead>
        <tbody>
{% for post in history_list%}
    {% if post.files%}
    <tr>
        <td>{{post.files | cut_redundant:"[']"   }}</td>
        <td>-</td>
        <td>-</td>
        <td>{{post.name_of_operation}}</td>
        <td>{{post.trash_bin | get_trash_name}}</td>
        <td>{{post.state}}</td>
    </tr>
    {% endif %}

    {% if post.start_folder %}
        <tr>
        <td>-</td>
        <td>{{post.pattern}}</td>
        <td>{{post.start_folder}}</td>
        <td>{{post.name_of_operation}}</td>
        <td>{{post.trash_bin| get_trash_name}} </td>
        <td>{{post.state}}</td>
    </tr>
    {% endif %}
{% endfor %}
        </tbody>
</table>
{% endblock %}

smart_rm/templates/smart_rm/regex.html
{% extends "smart_rm/base.html" %}
{% block content %}
<style>
    .regex-class{
        height:500px;
    }
</style>
<div class="regex-class">
        <form method="post" action="" class="form-inline text-center "> {% csrf_token %}
            <div class="container">
                <div class="form-group">
                    {{form.as_p}}
                    <button class="btn bg-primary" type="submit"> Add a task </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

smart_rm/templates/smart_rm/settings.html
{% extends "smart_rm/base.html" %}

{% block content %}
<style>
    .navbar{
        margin-bottom: 0;
    }
    .choice-class{
        height: 470px;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        font-size: x-large;
        margin-top: 70px;
        text-align: center;
    }
</style>
        <nav class="navbar navbar-inverse">
            <ul class="nb-top-2">
            {% for name in name_list %}
                <li class="li-nb-top-2"><a class="li-nb-top-2-a" href="/{{current_page}}/trashBin/{{name}}">{{name}}</a></li>
            {% endfor %}</ul>
        </nav>
    <div class="choice-class">
       <p>
           Choose a trash bin for showing settings!
       </p>
    </div>
{% endblock %}

smart_rm/templates/smart_rm/settings_with_trash_bin.html
{% extends "smart_rm/base.html" %}

{% block content %}
<style>
    .choice-class{
        height: 520px;
    }
    .but-position{
        margin-top: 5px;
         text-align: center;
    }
</style>
    <div class="choice-class">
        <form method="post" action="" class="form-inline text-center"> {% csrf_token %}
            <div class="container">
                <div class="form-group">
                    {{form.as_p}}
                </div>
            </div>

            <button class="btn bg-primary" type="submit"> Edit </button>

        </form>
        <div class="but-position">
            <form action="{% url 'remove' form.name.value %}">
                <button type="submit" class="btn btn-danger ">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

smart_rm/templates/smart_rm/show.html
{% extends "smart_rm/base.html" %}
{% block content %}

<style>
    .navbar{
        margin-bottom: 0;
    }
    .choice-class{
        height: 470px;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        font-size: x-large;
        margin-top: 70px;
        text-align: center;
    }
</style>
        <nav class="navbar navbar-inverse">
            <ul class="nb-top-2">
            {% for name in name_list %}
                <li class="li-nb-top-2"><a class="li-nb-top-2-a" href="/{{current_page}}/trashBin/{{name}}">{{name}}</a></li>
            {% endfor %}</ul>
        </nav>
    <div class="choice-class">
           Choose a trash bin for showing files in it!
       </p>
    </div>
{% endblock %}

smart_rm/templates/smart_rm/show_trash.html
{% extends "smart_rm/base.html" %}

{% block content %}

        <button class="btn bg-primary" id="delete_button">Delete!</button>
        <button class="btn btn-danger" id="delete_all_button">Delete all!</button>
        <button class="btn btn-primary" id="recover_button">Recover!</button>
        <button class="btn btn-danger" id="recover_all_button">Recover all!</button>
    <p></p>
<table class="table table-striped">
    <thead>
      <tr>
          <th></th>
          <th>Name</th>
          <th>Hash</th>
          <th>Path</th>
          <th>Type</th>
          <th>Size</th>
      </tr>
    </thead>
        <tbody>
    {% for file in arr_json_files %}
    <tr>
        <td>
        <input class="Checkbox" type="checkbox" id="{{file.hash}}" value="{{file.name}}">
        </td>
        <td>{{file.name}}</td>
        <td>{{file.hash}}</td>
        <td>{{file.path}}</td>
        <td>{{file.type}}</td>
        <td>{{file.size}} Bytes</td>
    </tr>
    {% endfor %}
        </tbody>
</table>
<script>
$('#delete_button').on('click', function (event) {
    var array_of_hashes = [];
    var array_of_names = [];
    var data = $('.Checkbox:checked').each(function(){
        array_of_hashes.push($(this).attr('id'));
        array_of_names.push($(this).val())
    });
    console.log(array_of_names, array_of_hashes);
    $.post('remove_from_trash', {hashes : array_of_hashes, names : array_of_names});
});

$('#delete_all_button').on('click', function (event) {
    var array_of_hashes = [];
    var array_of_names = [];
    var data = $('.Checkbox').each(function(){
        array_of_hashes.push($(this).attr('id'));
        array_of_names.push($(this).val())
    });
    console.log(array_of_hashes);
    $.post('remove_from_trash', {hashes : array_of_hashes, names : array_of_names});
});

$('#recover_all_button').on('click', function (event) {
    var array_of_hashes = [];
    var array_of_names = [];
    var data = $('.Checkbox').each(function(){
        array_of_hashes.push($(this).attr('id'));
        array_of_names.push($(this).val())
    });
    console.log(array_of_names, array_of_hashes);
    $.post('recover_from_trash', {hashes : array_of_hashes, names : array_of_names});
});

$('#recover_button').on('click', function (event) {
    var array_of_hashes = [];
    var array_of_names = [];
    var data = $('.Checkbox:checked').each(function(){
        array_of_hashes.push($(this).attr('id'));
        array_of_names.push($(this).val())
    });
    console.log(array_of_hashes);
    $.post('recover_from_trash', {hashes : array_of_hashes, names : array_of_names});
});

</script><script src="../../static/css/dist/jstree.min.js"></script>
{% endblock %}

smart_rm/templates/smart_rm/success.html
{% extends "smart_rm/base.html" %}

{% block content %}
<style>
    .choice-class{
        height: 470px;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        margin-top: 70px;
        text-align: center;
        font-size: 70px;
        color: #1b8dbb;
    }
</style>
    <div class="choice-class">
        <p class="choice-class">Success!</p>
    </div>
{% endblock %}

smart_rm/templates/smart_rm/tasks.html
{% extends "smart_rm/base.html" %}

{% load my_template_tag %}
{% block content %}
<table class="table table-striped">
    <thead>
      <tr>
          <th>Regular Expression</th>
          <th>Start directory</th>
          <th>Trash bin</th>
          <th>Execute!</th>
          <th>Delete!</th>
      </tr>
    </thead>
        <tbody>
        {% for reg_task in regular_tasks%}
        <tr>
            <td>{{reg_task.regular_expression}}</td>
            <td>{{reg_task.start_folder}}</td>
            <td>{{reg_task.current_trash_bin}}</td>
            <td>
                <button class="btn btn-primary" id="execute-{{reg_task.id}}">Execute!</button>
            </td>
            <td>
                <button class="btn btn-danger" id="delete-{{reg_task.id}}">Cancel!</button>
            </td>
        </tr>

    <script>
    $("#execute-{{reg_task.id}}").on('click', function (event) {
        var current_trash =  '{{reg_task.current_trash_bin}}';
        event.preventDefault();
        var data = {
            trash : current_trash,
            start_folder : '{{reg_task.start_folder}}',
            task_id : '{{reg_task.id}}',
            pattern : '{{reg_task.regular_expression}}'
        };
        console.log(data);
                $.post('execute_regular_task', data);
            });

    $("#delete-{{reg_task.id}}").on('click', function (event) {
        event.preventDefault();
                $.post('delete_regular_task', {task_id : '{{reg_task.id}}'});
            });

    </script><script src="../../static/css/dist/jstree.min.js"></script>
{% endfor %}

        </tbody>
</table>
<table class="table table-striped">
    <thead>
      <tr>
          <th>Files</th>
          <th>Trash bin</th>
          <th>Name of operation</th>
          <th>Execute!</th>
          <th>Delete!</th>
      </tr>
    </thead>
        <tbody>
{% for task in tasks_list%}
<tr>
            <td>{{task.files| cut_redundant:"[']"}}</td>
            <td>{{task.current_trash_bin}}</td>
            <td>{{task.name_of_operation}}</td>
            <td>
                <button class="btn btn-primary" id="execute-{{task.id}}">Execute!</button>
            </td>
            <td>
                <button class="btn btn-danger" id="delete-{{task.id}}">Cancel!</button>
            </td>
        </tr>
<script>
$("#execute-{{task.id}}").on('click', function (event) {
    var current_trash =  '{{task.current_trash_bin}}';
    event.preventDefault();
    var data = {
        trash : current_trash,
        files : '{{task.files}}',
        task_id : '{{task.id}}',
        operation : '{{task.name_of_operation}}',
        hashes : '{{task.hashes}}'
    };
    console.log(data);
            $.post('execute_task', data);
        });

$("#delete-{{task.id}}").on('click', function (event) {
    event.preventDefault();
            $.post('delete_task', {task_id : '{{task.id}}'});
        });

</script><script src="../../static/css/dist/jstree.min.js"></script>
{% endfor %}
        </tbody>
</table>

{% endblock %}

smart_rm/templates/smart_rm/trash_bin_confirm_delete.html
{% extends "smart_rm/base.html" %}

{% block content %}
<style>
    .choice-class{
        height: 470px;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        margin-top: 70px;
        text-align: center;
        font-size: x-large;
    }
</style>
<div class="choice-class">
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete trash "{{ object }}" ?</p>
        <input class="btn btn-danger" type="submit" value="Delete" />
    </form>
    </div>
{% endblock%}}